name: Deploy to K3s

on:
  # Triggered on push to "deploy" branch
  push:
    branches:
      - deploy
    paths:
      - 'k8s/**'
  # Can be triggered manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Applying Kubernetes objects
    runs-on: ubuntu-latest
    steps:
      - name: Configuring kubectl
        run: |-
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          mkdir -p ~/.local/bin/
          mv ./kubectl ~/.local/bin/
          mkdir -p ~/.kube
          echo "${KUBECONFIG_CONTENT}" > ~/.kube/config
          echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
        env:
          KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
      - uses: actions/checkout@v2
      - name: Reporting current status
        run: |-
          kubectl version
          kubectl get nodes
          kubectl get pods
          kubectl diff -f ./k8s/ || :
      - name: Applying Kubernetes objects
        run: |-
          kubectl apply -f ./k8s/
